### PR TITLE
Make chorus.Client gevent compatible

### PR DESCRIPTION
**Pull request by ackramer**
@wesc 

Pretty short PR. The only thing that ValueEvent and gevent.event.AsyncResult differ on is the exception they throw when timing out. I don't really like storing the exception type in self._timeout_exception_type but I couldn't think of a more robust way.

Also, the gevent stuff at the top of the file cannot be hidden away in the Client class. If you try to the gevent import won't be accessible.

Adrian

### CODE REVIEW

**Comment by wesc** [comment]
Minor restructuring... I would move the import statement into `Client.__init__` so that a WADE node (which imports chorus) doesn't necessarily also import gevent, even though it should be harmless.

Second, you can eliminate the special casing if you define in `Client.__init__` a ValueEvent class, a Timeout class, and a sleep function for each method. So something like:

```
if gevent_enabled:
    self._ValueEvent = gevent.AsyncResult
    self._Timeout = gevent.Timeout
    self._sleep = gevent.sleep
else:
    self._ValueEvent = ValueEvent
    self._Timeout = ValueEventTimeout
    self._sleep = lambda _: pass
```

And then you don't have to do `if` checks on whether or not we're using gevent in the rest of the class.

**Comment by ackramer** [comment]
@wesc only problem with that solution is that we need to treat the ValueEvent and AsyncResult differently when creating them. AsyncResults are not reusable and shouldn't be stored in a thread local. I don't think I can get around doing some inspection in the _ensure_value_event(...) function. Otherwise though I'll use your timeout / sleep variables.

will ask for your feedback again before I merge.

**Comment by ackramer** [comment]
@wesc 

Just pushed a change which I think cleans up the code a bit.

**Comment by wesc** [comment]
LGTM

**Pull request merged**
